# Generated by Django 4.0.1 on 2022-01-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automate_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('City', models.CharField(choices=[('mumbai', 'MUMBAI'), ('delhi', 'DELHI'), ('chennai', 'CHENNAI'), ('bangalore', 'BANGALORE'), ('kolkata', 'KOLKATA')], max_length=30)),
                ('Time', models.TimeField()),
            ],
        ),
    ]
